// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 06 Jan 2018 21:05:42 EST.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "pugl.h"
#include "cairo_gl.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// PuglEventFunc_d2bbaefb is a proxy for callback PuglEventFunc.
void PuglEventFunc_d2bbaefb(PuglView* view, PuglEvent* event);

