// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 06 Jan 2018 19:12:26 EST.
// By https://git.io/c-for-go. DO NOT EDIT.

package pugl

/*
#cgo pkg-config: cairo
#include "pugl.h"
#include "cairo_gl.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// HaveGl as defined in cairo-go/<predefine>:24
	HaveGl = 1
	// HaveCairo as defined in cairo-go/<predefine>:26
	HaveCairo = 1
)

// Status as declared in pugl/pugl.h:79
type Status int32

// Status enumeration from pugl/pugl.h:79
const (
	Success Status = iota
)

// ContextType as declared in pugl/pugl.h:88
type ContextType int32

// ContextType enumeration from pugl/pugl.h:88
const (
	ContextGL      ContextType = 1
	ContextCairo   ContextType = 2
	ContextCairoGL ContextType = 3
)

// Char as declared in pugl/pugl.h:97
type Char int32

// Char enumeration from pugl/pugl.h:97
const (
	CharBackspace Char = 8
	CharEscape    Char = 27
	CharDelete    Char = 127
)

// Mod as declared in pugl/pugl.h:107
type Mod int32

// Mod enumeration from pugl/pugl.h:107
const (
	ModShift Mod = 1
	ModCtrl  Mod = 2
	ModAlt   Mod = 4
	ModSuper Mod = 8
)

// Key as declared in pugl/pugl.h:143
type Key int32

// Key enumeration from pugl/pugl.h:143
const (
	KeyF1       Key = 57344
	KeyF2       Key = 57345
	KeyF3       Key = 57346
	KeyF4       Key = 57347
	KeyF5       Key = 57348
	KeyF6       Key = 57349
	KeyF7       Key = 57350
	KeyF8       Key = 57351
	KeyF9       Key = 57352
	KeyF10      Key = 57353
	KeyF11      Key = 57354
	KeyF12      Key = 57355
	KeyLeft     Key = 57356
	KeyUp       Key = 57357
	KeyRight    Key = 57358
	KeyDown     Key = 57359
	KeyPageUp   Key = 57360
	KeyPageDown Key = 57361
	KeyHome     Key = 57362
	KeyEnd      Key = 57363
	KeyInsert   Key = 57364
	KeyShift    Key = 57365
	KeyCtrl     Key = 57366
	KeyAlt      Key = 57367
	KeySuper    Key = 57368
)

// EventType as declared in pugl/pugl.h:163
type EventType int32

// EventType enumeration from pugl/pugl.h:163
const (
	Nothing       EventType = iota
	ButtonPress   EventType = 1
	ButtonRelease EventType = 2
	Configure     EventType = 3
	Expose        EventType = 4
	Close         EventType = 5
	KeyPress      EventType = 6
	KeyRelease    EventType = 7
	EnterNotify   EventType = 8
	LeaveNotify   EventType = 9
	MotionNotify  EventType = 10
	Scroll        EventType = 11
	FocusIn       EventType = 12
	FocusOut      EventType = 13
)

// EventFlag as declared in pugl/pugl.h:167
type EventFlag int32

// EventFlag enumeration from pugl/pugl.h:167
const (
	IsSendEvent EventFlag = 1
)

// CrossingMode as declared in pugl/pugl.h:176
type CrossingMode int32

// CrossingMode enumeration from pugl/pugl.h:176
const (
	CrossingNormal CrossingMode = iota
	CrossingGrab   CrossingMode = 1
	CrossingUngrab CrossingMode = 2
)
