// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 06 Jan 2018 19:12:26 EST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package pugl provides Go bindings for PUGL — a minimal portable API for OpenGL and Cairo interfaces.
*/
package pugl
