package cairo

/*
#cgo CFLAGS: -DCAIRO_HAS_FT_FONT
#cgo CFLAGS: -DCAIRO_HAS_FC_FONT
#cgo CFLAGS: -DCAIRO_HAS_IMAGE_SURFACE
#cgo CFLAGS: -DCAIRO_HAS_MIME_SURFACE
#cgo CFLAGS: -DCAIRO_HAS_PNG_FUNCTIONS
#cgo CFLAGS: -DCAIRO_HAS_RECORDING_SURFACE
#cgo CFLAGS: -DCAIRO_HAS_SCRIPT_SURFACE
#cgo CFLAGS: -DCAIRO_HAS_TEE_SURFACE
#cgo CFLAGS: -DCAIRO_HAS_USER_FONT

#include "include/cairo.h"
#include "include/cairo-deprecated.h"
*/
import "C"

// #undef CAIRO_HAS_GOBJECT_FUNCTIONS
// #undef CAIRO_HAS_BEOS_SURFACE
// #undef CAIRO_HAS_COGL_SURFACE
// #undef CAIRO_HAS_DIRECTFB_SURFACE
// #undef CAIRO_HAS_DRM_SURFACE
// #undef CAIRO_HAS_EGL_FUNCTIONS
// #undef CAIRO_HAS_GALLIUM_SURFACE
// #undef CAIRO_HAS_GLESV2_SURFACE
// #undef CAIRO_HAS_GLX_FUNCTIONS
// #undef CAIRO_HAS_GL_SURFACE
// #undef CAIRO_HAS_OS2_SURFACE
// #undef CAIRO_HAS_QT_SURFACE
// #undef CAIRO_HAS_SKIA_SURFACE
// #undef CAIRO_HAS_VG_SURFACE
// #undef CAIRO_HAS_WGL_FUNCTIONS
// #undef CAIRO_HAS_WIN32_FONT
// #undef CAIRO_HAS_WIN32_SURFACE
// #undef CAIRO_HAS_XCB_SHM_FUNCTIONS
// #undef CAIRO_HAS_XCB_SURFACE
// #undef CAIRO_HAS_XLIB_SURFACE
// #undef CAIRO_HAS_XLIB_XCB_FUNCTIONS
// #undef CAIRO_HAS_XLIB_XRENDER_SURFACE
// #undef CAIRO_HAS_XML_SURFACE
