// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 11 Jan 2018 16:22:52 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package cairo provides Go bindings for Cairo.
*/
package cairo
