// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 06 Jan 2018 18:31:25 EST.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "cairo.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// cairo_destroy_func_t_6936ee15 is a proxy for callback cairo_destroy_func_t.
void cairo_destroy_func_t_6936ee15(void* data);

// cairo_write_func_t_f4dfc69 is a proxy for callback cairo_write_func_t.
cairo_status_t cairo_write_func_t_f4dfc69(void* closure, unsigned char* data, unsigned int length);

// cairo_read_func_t_69800aa2 is a proxy for callback cairo_read_func_t.
cairo_status_t cairo_read_func_t_69800aa2(void* closure, unsigned char* data, unsigned int length);

// cairo_user_scaled_font_init_func_t_87c5d9cb is a proxy for callback cairo_user_scaled_font_init_func_t.
cairo_status_t cairo_user_scaled_font_init_func_t_87c5d9cb(cairo_scaled_font_t* scaled_font, cairo_t* cr, cairo_font_extents_t* extents);

// cairo_user_scaled_font_render_glyph_func_t_32c7be76 is a proxy for callback cairo_user_scaled_font_render_glyph_func_t.
cairo_status_t cairo_user_scaled_font_render_glyph_func_t_32c7be76(cairo_scaled_font_t* scaled_font, unsigned long int glyph, cairo_t* cr, cairo_text_extents_t* extents);

// cairo_user_scaled_font_text_to_glyphs_func_t_5fc4fffd is a proxy for callback cairo_user_scaled_font_text_to_glyphs_func_t.
cairo_status_t cairo_user_scaled_font_text_to_glyphs_func_t_5fc4fffd(cairo_scaled_font_t* scaled_font, char* utf8, int utf8_len, cairo_glyph_t** glyphs, int* num_glyphs, cairo_text_cluster_t** clusters, int* num_clusters, cairo_text_cluster_flags_t* cluster_flags);

// cairo_user_scaled_font_unicode_to_glyph_func_t_d4a3aae6 is a proxy for callback cairo_user_scaled_font_unicode_to_glyph_func_t.
cairo_status_t cairo_user_scaled_font_unicode_to_glyph_func_t_d4a3aae6(cairo_scaled_font_t* scaled_font, unsigned long int unicode, unsigned long int* glyph_index);

// cairo_surface_observer_callback_t_9f372381 is a proxy for callback cairo_surface_observer_callback_t.
void cairo_surface_observer_callback_t_9f372381(cairo_surface_t* observer, cairo_surface_t* target, void* data);

// cairo_raster_source_acquire_func_t_e7404447 is a proxy for callback cairo_raster_source_acquire_func_t.
cairo_surface_t* cairo_raster_source_acquire_func_t_e7404447(cairo_pattern_t* pattern, void* callback_data, cairo_surface_t* target, cairo_rectangle_int_t* extents);

// cairo_raster_source_release_func_t_659bfe43 is a proxy for callback cairo_raster_source_release_func_t.
void cairo_raster_source_release_func_t_659bfe43(cairo_pattern_t* pattern, void* callback_data, cairo_surface_t* surface);

// cairo_raster_source_snapshot_func_t_518a3707 is a proxy for callback cairo_raster_source_snapshot_func_t.
cairo_status_t cairo_raster_source_snapshot_func_t_518a3707(cairo_pattern_t* pattern, void* callback_data);

// cairo_raster_source_copy_func_t_84d80d8b is a proxy for callback cairo_raster_source_copy_func_t.
cairo_status_t cairo_raster_source_copy_func_t_84d80d8b(cairo_pattern_t* pattern, void* callback_data, cairo_pattern_t* other);

// cairo_raster_source_finish_func_t_ece7e85b is a proxy for callback cairo_raster_source_finish_func_t.
void cairo_raster_source_finish_func_t_ece7e85b(cairo_pattern_t* pattern, void* callback_data);

