// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 06 Jan 2018 21:05:42 EST.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void cairo_destroy_func_t_6936ee15(void* data) {
	destroyFunc6936EE15(data);
}

cairo_status_t cairo_write_func_t_f4dfc69(void* closure, unsigned char* data, unsigned int length) {
	return writeFuncF4DFC69(closure, data, length);
}

cairo_status_t cairo_read_func_t_69800aa2(void* closure, unsigned char* data, unsigned int length) {
	return readFunc69800AA2(closure, data, length);
}

cairo_status_t cairo_user_scaled_font_init_func_t_87c5d9cb(cairo_scaled_font_t* scaled_font, cairo_t* cr, cairo_font_extents_t* extents) {
	return userScaledFontInitFunc87C5D9CB(scaled_font, cr, extents);
}

cairo_status_t cairo_user_scaled_font_render_glyph_func_t_32c7be76(cairo_scaled_font_t* scaled_font, unsigned long int glyph, cairo_t* cr, cairo_text_extents_t* extents) {
	return userScaledFontRenderGlyphFunc32C7BE76(scaled_font, glyph, cr, extents);
}

cairo_status_t cairo_user_scaled_font_text_to_glyphs_func_t_5fc4fffd(cairo_scaled_font_t* scaled_font, char* utf8, int utf8_len, cairo_glyph_t** glyphs, int* num_glyphs, cairo_text_cluster_t** clusters, int* num_clusters, cairo_text_cluster_flags_t* cluster_flags) {
	return userScaledFontTextToGlyphsFunc5FC4FFFD(scaled_font, utf8, utf8_len, glyphs, num_glyphs, clusters, num_clusters, cluster_flags);
}

cairo_status_t cairo_user_scaled_font_unicode_to_glyph_func_t_d4a3aae6(cairo_scaled_font_t* scaled_font, unsigned long int unicode, unsigned long int* glyph_index) {
	return userScaledFontUnicodeToGlyphFuncD4A3AAE6(scaled_font, unicode, glyph_index);
}

void cairo_surface_observer_callback_t_9f372381(cairo_surface_t* observer, cairo_surface_t* target, void* data) {
	surfaceObserverCallback9F372381(observer, target, data);
}

cairo_surface_t* cairo_raster_source_acquire_func_t_e7404447(cairo_pattern_t* pattern, void* callback_data, cairo_surface_t* target, cairo_rectangle_int_t* extents) {
	return rasterSourceAcquireFuncE7404447(pattern, callback_data, target, extents);
}

void cairo_raster_source_release_func_t_659bfe43(cairo_pattern_t* pattern, void* callback_data, cairo_surface_t* surface) {
	rasterSourceReleaseFunc659BFE43(pattern, callback_data, surface);
}

cairo_status_t cairo_raster_source_snapshot_func_t_518a3707(cairo_pattern_t* pattern, void* callback_data) {
	return rasterSourceSnapshotFunc518A3707(pattern, callback_data);
}

cairo_status_t cairo_raster_source_copy_func_t_84d80d8b(cairo_pattern_t* pattern, void* callback_data, cairo_pattern_t* other) {
	return rasterSourceCopyFunc84D80D8B(pattern, callback_data, other);
}

void cairo_raster_source_finish_func_t_ece7e85b(cairo_pattern_t* pattern, void* callback_data) {
	rasterSourceFinishFuncECE7E85B(pattern, callback_data);
}

