// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 06 Jan 2018 18:31:25 EST.
// By https://git.io/c-for-go. DO NOT EDIT.

package cairo

/*
#cgo pkg-config: cairo
#include "cairo.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// Version as defined in cairo/cairo.h:68
	Version = 11509
	// TagDest as defined in cairo/cairo.h:1031
	TagDest = "cairo.dest"
	// TagLink as defined in cairo/cairo.h:1032
	TagLink = "Link"
	// MimeTypeJpeg as defined in cairo/cairo.h:2448
	MimeTypeJpeg = "image/jpeg"
	// MimeTypePng as defined in cairo/cairo.h:2449
	MimeTypePng = "image/png"
	// MimeTypeJp2 as defined in cairo/cairo.h:2450
	MimeTypeJp2 = "image/jp2"
	// MimeTypeUri as defined in cairo/cairo.h:2451
	MimeTypeUri = "text/x-uri"
	// MimeTypeUniqueId as defined in cairo/cairo.h:2452
	MimeTypeUniqueId = "application/x-cairo.uuid"
	// MimeTypeJbig2 as defined in cairo/cairo.h:2453
	MimeTypeJbig2 = "application/x-cairo.jbig2"
	// MimeTypeJbig2Global as defined in cairo/cairo.h:2454
	MimeTypeJbig2Global = "application/x-cairo.jbig2-global"
	// MimeTypeJbig2GlobalId as defined in cairo/cairo.h:2455
	MimeTypeJbig2GlobalId = "application/x-cairo.jbig2-global-id"
	// MimeTypeCcittFax as defined in cairo/cairo.h:2456
	MimeTypeCcittFax = "image/g3fax"
	// MimeTypeCcittFaxParams as defined in cairo/cairo.h:2457
	MimeTypeCcittFaxParams = "application/x-cairo.ccitt.params"
	// MimeTypeEps as defined in cairo/cairo.h:2458
	MimeTypeEps = "application/postscript"
	// MimeTypeEpsParams as defined in cairo/cairo.h:2459
	MimeTypeEpsParams = "application/x-cairo.eps.params"
	// VersionMajor as defined in cairo/cairo-version.h:4
	VersionMajor = 1
	// VersionMinor as defined in cairo/cairo-version.h:5
	VersionMinor = 15
	// VersionMicro as defined in cairo/cairo-version.h:6
	VersionMicro = 9
	// HasFcFont as defined in cairo/cairo-features.h:5
	HasFcFont = 1
	// HasFtFont as defined in cairo/cairo-features.h:6
	HasFtFont = 1
	// HasGobjectFunctions as defined in cairo/cairo-features.h:7
	HasGobjectFunctions = 1
	// HasImageSurface as defined in cairo/cairo-features.h:8
	HasImageSurface = 1
	// HasMimeSurface as defined in cairo/cairo-features.h:9
	HasMimeSurface = 1
	// HasObserverSurface as defined in cairo/cairo-features.h:10
	HasObserverSurface = 1
	// HasPdfSurface as defined in cairo/cairo-features.h:11
	HasPdfSurface = 1
	// HasPngFunctions as defined in cairo/cairo-features.h:12
	HasPngFunctions = 1
	// HasPsSurface as defined in cairo/cairo-features.h:13
	HasPsSurface = 1
	// HasRecordingSurface as defined in cairo/cairo-features.h:16
	HasRecordingSurface = 1
	// HasScriptSurface as defined in cairo/cairo-features.h:17
	HasScriptSurface = 1
	// HasSvgSurface as defined in cairo/cairo-features.h:18
	HasSvgSurface = 1
	// HasUserFont as defined in cairo/cairo-features.h:19
	HasUserFont = 1
	// HasXlibSurface as defined in cairo/cairo-features.h:20
	HasXlibSurface = 1
	// HasXlibXrenderSurface as defined in cairo/cairo-features.h:21
	HasXlibXrenderSurface = 1
)

// Status as declared in cairo/cairo.h:361
type Status int32

// Status enumeration from cairo/cairo.h:361
const (
	StatusSuccess                 Status = iota
	StatusNoMemory                Status = 1
	StatusInvalidRestore          Status = 2
	StatusInvalidPopGroup         Status = 3
	StatusNoCurrentPoint          Status = 4
	StatusInvalidMatrix           Status = 5
	StatusInvalidStatus           Status = 6
	StatusNullPointer             Status = 7
	StatusInvalidString           Status = 8
	StatusInvalidPathData         Status = 9
	StatusReadError               Status = 10
	StatusWriteError              Status = 11
	StatusSurfaceFinished         Status = 12
	StatusSurfaceTypeMismatch     Status = 13
	StatusPatternTypeMismatch     Status = 14
	StatusInvalidContent          Status = 15
	StatusInvalidFormat           Status = 16
	StatusInvalidVisual           Status = 17
	StatusFileNotFound            Status = 18
	StatusInvalidDash             Status = 19
	StatusInvalidDscComment       Status = 20
	StatusInvalidIndex            Status = 21
	StatusClipNotRepresentable    Status = 22
	StatusTempFileError           Status = 23
	StatusInvalidStride           Status = 24
	StatusFontTypeMismatch        Status = 25
	StatusUserFontImmutable       Status = 26
	StatusUserFontError           Status = 27
	StatusNegativeCount           Status = 28
	StatusInvalidClusters         Status = 29
	StatusInvalidSlant            Status = 30
	StatusInvalidWeight           Status = 31
	StatusInvalidSize             Status = 32
	StatusUserFontNotImplemented  Status = 33
	StatusDeviceTypeMismatch      Status = 34
	StatusDeviceError             Status = 35
	StatusInvalidMeshConstruction Status = 36
	StatusDeviceFinished          Status = 37
	StatusJbig2GlobalMissing      Status = 38
	StatusPngError                Status = 39
	StatusFreetypeError           Status = 40
	StatusWin32GdiError           Status = 41
	StatusTagError                Status = 42
	StatusLastStatus              Status = 43
)

// Content as declared in cairo/cairo.h:383
type Content int32

// Content enumeration from cairo/cairo.h:383
const (
	ContentColor      Content = 4096
	ContentAlpha      Content = 8192
	ContentColorAlpha Content = 12288
)

// Format as declared in cairo/cairo.h:424
type Format int32

// Format enumeration from cairo/cairo.h:424
const (
	FormatInvalid  Format = -1
	FormatArgb32   Format = 0
	FormatRgb24    Format = 1
	FormatA8       Format = 2
	FormatA1       Format = 3
	FormatRgb16565 Format = 4
	FormatRgb30    Format = 5
)

// Operator as declared in cairo/cairo.h:647
type Operator int32

// Operator enumeration from cairo/cairo.h:647
const (
	OperatorClear         Operator = iota
	OperatorSource        Operator = 1
	OperatorOver          Operator = 2
	OperatorIn            Operator = 3
	OperatorOut           Operator = 4
	OperatorAtop          Operator = 5
	OperatorDest          Operator = 6
	OperatorDestOver      Operator = 7
	OperatorDestIn        Operator = 8
	OperatorDestOut       Operator = 9
	OperatorDestAtop      Operator = 10
	OperatorXor           Operator = 11
	OperatorAdd           Operator = 12
	OperatorSaturate      Operator = 13
	OperatorMultiply      Operator = 14
	OperatorScreen        Operator = 15
	OperatorOverlay       Operator = 16
	OperatorDarken        Operator = 17
	OperatorLighten       Operator = 18
	OperatorColorDodge    Operator = 19
	OperatorColorBurn     Operator = 20
	OperatorHardLight     Operator = 21
	OperatorSoftLight     Operator = 22
	OperatorDifference    Operator = 23
	OperatorExclusion     Operator = 24
	OperatorHslHue        Operator = 25
	OperatorHslSaturation Operator = 26
	OperatorHslColor      Operator = 27
	OperatorHslLuminosity Operator = 28
)

// Antialias as declared in cairo/cairo.h:721
type Antialias int32

// Antialias enumeration from cairo/cairo.h:721
const (
	AntialiasDefault  Antialias = iota
	AntialiasNone     Antialias = 1
	AntialiasGray     Antialias = 2
	AntialiasSubpixel Antialias = 3
	AntialiasFast     Antialias = 4
	AntialiasGood     Antialias = 5
	AntialiasBest     Antialias = 6
)

// FillRule as declared in cairo/cairo.h:756
type FillRule int32

// FillRule enumeration from cairo/cairo.h:756
const (
	FillRuleWinding FillRule = iota
	FillRuleEvenOdd FillRule = 1
)

// LineCap as declared in cairo/cairo.h:780
type LineCap int32

// LineCap enumeration from cairo/cairo.h:780
const (
	LineCapButt   LineCap = iota
	LineCapRound  LineCap = 1
	LineCapSquare LineCap = 2
)

// LineJoin as declared in cairo/cairo.h:804
type LineJoin int32

// LineJoin enumeration from cairo/cairo.h:804
const (
	LineJoinMiter LineJoin = iota
	LineJoinRound LineJoin = 1
	LineJoinBevel LineJoin = 2
)

// TextClusterFlags as declared in cairo/cairo.h:1162
type TextClusterFlags int32

// TextClusterFlags enumeration from cairo/cairo.h:1162
const (
	TextClusterFlagBackward TextClusterFlags = 1
)

// FontSlant as declared in cairo/cairo.h:1267
type FontSlant int32

// FontSlant enumeration from cairo/cairo.h:1267
const (
	FontSlantNormal  FontSlant = iota
	FontSlantItalic  FontSlant = 1
	FontSlantOblique FontSlant = 2
)

// FontWeight as declared in cairo/cairo.h:1281
type FontWeight int32

// FontWeight enumeration from cairo/cairo.h:1281
const (
	FontWeightNormal FontWeight = iota
	FontWeightBold   FontWeight = 1
)

// SubpixelOrder as declared in cairo/cairo.h:1308
type SubpixelOrder int32

// SubpixelOrder enumeration from cairo/cairo.h:1308
const (
	SubpixelOrderDefault SubpixelOrder = iota
	SubpixelOrderRgb     SubpixelOrder = 1
	SubpixelOrderBgr     SubpixelOrder = 2
	SubpixelOrderVrgb    SubpixelOrder = 3
	SubpixelOrderVbgr    SubpixelOrder = 4
)

// HintStyle as declared in cairo/cairo.h:1340
type HintStyle int32

// HintStyle enumeration from cairo/cairo.h:1340
const (
	HintStyleDefault HintStyle = iota
	HintStyleNone    HintStyle = 1
	HintStyleSlight  HintStyle = 2
	HintStyleMedium  HintStyle = 3
	HintStyleFull    HintStyle = 4
)

// HintMetrics as declared in cairo/cairo.h:1361
type HintMetrics int32

// HintMetrics enumeration from cairo/cairo.h:1361
const (
	HintMetricsDefault HintMetrics = iota
	HintMetricsOff     HintMetrics = 1
	HintMetricsOn      HintMetrics = 2
)

// FontType as declared in cairo/cairo.h:1571
type FontType int32

// FontType enumeration from cairo/cairo.h:1571
const (
	FontTypeToy    FontType = iota
	FontTypeFt     FontType = 1
	FontTypeWin32  FontType = 2
	FontTypeQuartz FontType = 3
	FontTypeUser   FontType = 4
)

// PathDataType as declared in cairo/cairo.h:1991
type PathDataType int32

// PathDataType enumeration from cairo/cairo.h:1991
const (
	PathMoveTo    PathDataType = iota
	PathLineTo    PathDataType = 1
	PathCurveTo   PathDataType = 2
	PathClosePath PathDataType = 3
)

// DeviceType as declared in cairo/cairo.h:2167
type DeviceType int32

// DeviceType enumeration from cairo/cairo.h:2167
const (
	DeviceTypeDrm     DeviceType = iota
	DeviceTypeGl      DeviceType = 1
	DeviceTypeScript  DeviceType = 2
	DeviceTypeXcb     DeviceType = 3
	DeviceTypeXlib    DeviceType = 4
	DeviceTypeXml     DeviceType = 5
	DeviceTypeCogl    DeviceType = 6
	DeviceTypeWin32   DeviceType = 7
	DeviceTypeInvalid DeviceType = -1
)

// SurfaceObserverMode as declared in cairo/cairo.h:2245
type SurfaceObserverMode int32

// SurfaceObserverMode enumeration from cairo/cairo.h:2245
const (
	SurfaceObserverNormal           SurfaceObserverMode = iota
	SurfaceObserverRecordOperations SurfaceObserverMode = 1
)

// SurfaceType as declared in cairo/cairo.h:2417
type SurfaceType int32

// SurfaceType enumeration from cairo/cairo.h:2417
const (
	SurfaceTypeImage         SurfaceType = iota
	SurfaceTypePdf           SurfaceType = 1
	SurfaceTypePs            SurfaceType = 2
	SurfaceTypeXlib          SurfaceType = 3
	SurfaceTypeXcb           SurfaceType = 4
	SurfaceTypeGlitz         SurfaceType = 5
	SurfaceTypeQuartz        SurfaceType = 6
	SurfaceTypeWin32         SurfaceType = 7
	SurfaceTypeBeos          SurfaceType = 8
	SurfaceTypeDirectfb      SurfaceType = 9
	SurfaceTypeSvg           SurfaceType = 10
	SurfaceTypeOs2           SurfaceType = 11
	SurfaceTypeWin32Printing SurfaceType = 12
	SurfaceTypeQuartzImage   SurfaceType = 13
	SurfaceTypeScript        SurfaceType = 14
	SurfaceTypeQt            SurfaceType = 15
	SurfaceTypeRecording     SurfaceType = 16
	SurfaceTypeVg            SurfaceType = 17
	SurfaceTypeGl            SurfaceType = 18
	SurfaceTypeDrm           SurfaceType = 19
	SurfaceTypeTee           SurfaceType = 20
	SurfaceTypeXml           SurfaceType = 21
	SurfaceTypeSkia          SurfaceType = 22
	SurfaceTypeSubsurface    SurfaceType = 23
	SurfaceTypeCogl          SurfaceType = 24
)

// PatternType as declared in cairo/cairo.h:2825
type PatternType int32

// PatternType enumeration from cairo/cairo.h:2825
const (
	PatternTypeSolid        PatternType = iota
	PatternTypeSurface      PatternType = 1
	PatternTypeLinear       PatternType = 2
	PatternTypeRadial       PatternType = 3
	PatternTypeMesh         PatternType = 4
	PatternTypeRasterSource PatternType = 5
)

// Extend as declared in cairo/cairo.h:2915
type Extend int32

// Extend enumeration from cairo/cairo.h:2915
const (
	ExtendNone    Extend = iota
	ExtendRepeat  Extend = 1
	ExtendReflect Extend = 2
	ExtendPad     Extend = 3
)

// Filter as declared in cairo/cairo.h:2950
type Filter int32

// Filter enumeration from cairo/cairo.h:2950
const (
	FilterFast     Filter = iota
	FilterGood     Filter = 1
	FilterBest     Filter = 2
	FilterNearest  Filter = 3
	FilterBilinear Filter = 4
	FilterGaussian Filter = 5
)

// RegionOverlap as declared in cairo/cairo.h:3089
type RegionOverlap int32

// RegionOverlap enumeration from cairo/cairo.h:3089
const (
	RegionOverlapIn   RegionOverlap = iota
	RegionOverlapOut  RegionOverlap = 1
	RegionOverlapPart RegionOverlap = 2
)
