// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 06 Jan 2018 18:31:25 EST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package cairo provides Go bindings for Cairo.
*/
package cairo
