// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 12 Dec 2017 17:29:45 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package cairo provides Go bindings for Cairo.
*/
package cairo
